apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-pvc

spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  storageClassName: do-block-storage-retain
  resources:
    requests:
      storage: 1Gi