---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  # namespace: dov-ns
  labels:
    app: dov
    name: dov-cm
data:
  app_name: "My Dov Bear"

---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  # namespace: dov-ns
  labels:
    app: dov
    name: dov-secret
type: Opaque
data:
  app_instance: bXlzZWNyZXRwdw==