---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  # namespace: dov-ns
  labels:
    app: dov
    name: dov-deploy
spec:
  # num of instances
  replicas: 3

  # select pods belonging to this deployment
  selector:
    matchLabels:
      app: dov
      name: dov-po

  # pod template
  template: 
    metadata:
      name: dov-po
      labels:
        app: dov
        name: dov-po
    spec:
      containers:
      - name: dov-container
        image: stackupiss/dov-bear:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          valueFrom:
            configMapKeyRef:
              name: dov-cm
              key: app_name
        - name: INSTANCE_HASH
          valueFrom:
            secretKeyRef:
              name: dov-secret
              key: app_instance
            # fieldRef:
              # fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    app: dov
    name: dov-svc
spec:
  type: LoadBalancer
  selector:
    app: dov
    name: dov-po
  ports:
  - port: 8080
    targetPort: 3000