apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: dov-ns

commonLabels:
  env: prod

replicas:
- name: dov-deploy
  count: 3

generatorOptions:
  labels:
    env: prod

configMapGenerator:
  - name: dov-cm 
    behavior: create
    literals:
    - INSTANCE_NAME=prod-dov-bear
