---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
  labels:
    app: minio
    name: minio-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
  labels:
    app: minio
    name: minio-cm
data:
  MINIO_ROOT_USER: bWluaW8tcm9vdC11c2Vy

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
  labels:
    app: minio
    name: minio-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: bWluaW8tcm9vdC1wYXNzd29yZA==

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minio-ns
  labels:
    app: minio
    name: minio-ing
spec:
  ingressClassName: nginx
  rules:
  - host: data-139.59.195.8.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              name: data-port
  - host: console-139.59.195.8.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              name: web-port
