---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
      app: bgg
      name: bggdb-po
    spec:
      containers:
      - name: bgg-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 0
      maxUnavailable: 1
  template: 
    metadata:
      name: bggapp-po
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bgg-svc
  labels:
    app: bgg
    name: bgg-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    app: bgg
    name: bggapp-po
  ports:
  - port: 3000
    targetPort: 3000