apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: csns 
  labels:
    app: cs
    name: cs-pvc

spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage-retain 
  resources:
    requests:
      storage: 1Gi