networks:
  my-net:

volumes:
  my-vol:

services:
  mydb:
    image: stackupiss/northwind-db:v1
    build:
      context: app
    volumes:
    - my-vol:/var/lib/mysql
    networks:
    - my-net

  myapp:
    image: stackupiss/northwind-app:v1
    networks:
    - my-net
    environment:
    - DB_HOST=mydb
    - DB_USER=root
    - DB_PASSWORD=changeit
    ports:
    - 8000-9000:3000

