apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: my-dev


build:
  artifacts:
  - image: chukmunnlee/go-dov-bear
    context: src
  tagPolicy:
    gitCommit: {}
    # envTemplate:
    #   template: " {{ .IMAGE_TAG }}"
  local:
    tryImportMissing: true
    push:
    useBuildkit:

manifests:
  kustomize:
    paths:
    - prod

deploy:
  kubectl:
    flags:
      # global:
      # - --kubeconfig
      # - /my/kubconfig/config
      apply:
      - -oyaml
      delete:
      - --force
      - -- grace-period-0

portForward:
- resourceType: Service
  resourceName: dov-svc
  namespace: dov-ns
  port: 3000
  localPort: 8080